name: "Build and Github Pages Deploy"
on:
  push:
    branches:
      - main
      # - "feature/**"
env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: godot-game-template
  ITCH_IO: false #set to true if you want to enable automatic itch.io deploy

jobs:
  gotdot-web-export:
    name: Godot Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          mv -v /root/.local/share/godot/templates/* ~/.local/share/godot/export_templates/
      - name: Web Build
        run: |
          mkdir -v -p builds/web
          godot -v --headless --export-release "Web" ./builds/web/index.html
      - name: Add COI Service Worker
        run: |
          wget https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.min.js -O ./builds/web/coi-serviceworker.min.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: builds/web
          retention-days: 1
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web
          path: builds/web
          retention-days: 1

  github-pages-deploy:
    needs: gotdot-web-export
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
